#index:
#    path: /
#    controller: App\Controller\DefaultController::index


api_login_check:
    path: /api/login
get_orders_by_user:
  path: /api/orders/user/{userId}
  controller: App\Controller\GetOrdersByUserController::class
  methods: ['GET']
  defaults:
    _api_resource_class: 'App\Entity\Order'
    _api_item_operation_name: 'getOrdersByUser'
    _api_receive: true
    _api_collection_operation: true